Null annotations and `in string` args
GmodNET/GmodDotNet pull request #142
Opened 2023-01-24 18:38 UTC by GlebChili

Removes redundant `in string` parameters from the API surface and enables nullable annotations and nullable warnings as errors
for both GmodNET.API and core GmodNET.

Closes #141 
Closes #84

2023-01-24 18:43 UTC, SupinePandora43 commented
This is cool, but what do you think about `ReadOnlySpan<char>` and `ReadOnlySpan<byte>` (utf8) ? Might improve performance in some scenarios.

2023-01-24 18:45 UTC, AaronJThompson approved these changes
Looks good to me!

2023-01-24 18:49 UTC, GlebChili commented
@SupinePandora43 I like the idea about `ReadOnlySpan`, but I think it is a good idea to ship them as part of version 1.1.0. Open the issue, and I will also welcome PR from you.

2023-01-24 19:02 UTC, SupinePandora43 requested changes
I haven't been active lately (in general), I'll try to fix that

2023-01-24 19:02 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/GameConsoleWriter.cs
> +            if (!String.IsNullOrEmpty(value) && Msg is not null)
I think this is redundant

2023-01-24 19:02 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/Lua.cs
> +            if (top is null)
Can we not check it every call? Or is it eliminated by JIT?

2023-01-24 19:02 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/Startup.cs
> +                    version_codename = full_assembly_version!.Split("+")[1].Split(".")[1];
Why there's `!` if `full_assembly_version` isn't nullable and simply can't be `null` because of `?? string.Empty`?

2023-01-24 19:02 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/GloabalContext.cs
> +                    IModule? current_module = Activator.CreateInstance(t) as IModule;
Why it's nullable?

2023-01-24 19:03 UTC, SupinePandora43 commented
> @SupinePandora43 I like the idea about `ReadOnlySpan`, but I think it is a good idea to ship them as part of version 1.1.0. Open the issue, and I will also welcome PR from you.

I'll create few feature requests issues with ideas i came up with.

2023-01-24 19:04 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/GameConsoleWriter.cs
> +            if (!String.IsNullOrEmpty(value) && Msg is not null)
Maybe, but C# null checker is not satisfied otherwise.

2023-01-24 19:05 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/Lua.cs
> +            if (top is null)
JIT will eliminate checks after few iterations

2023-01-24 19:05 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/Startup.cs
> +                    version_codename = full_assembly_version!.Split("+")[1].Split(".")[1];
Yeah, I will fix it in a moment.

2023-01-24 19:08 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/GloabalContext.cs
> +                    IModule? current_module = Activator.CreateInstance(t) as IModule;
CreateInstance has null annotation on return type: https://learn.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=net-7.0#system-activator-createinstance(system-type)

2023-01-24 19:11 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/Startup.cs
> +                    version_codename = full_assembly_version!.Split("+")[1].Split(".")[1];
Fixed!

2023-01-24 19:17 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/GloabalContext.cs
> +                    IModule? current_module = Activator.CreateInstance(t) as IModule;
Can you add `!` somewhere to make it not nullable? 😅

2023-01-24 19:19 UTC, SupinePandora43 commented on gm_dotnet_managed/GmodNET/Lua.cs
> +            if (top is null)
I think we should check it. (Performance regressions)

2023-01-24 19:21 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/GloabalContext.cs
> +                    IModule? current_module = Activator.CreateInstance(t) as IModule;
But why? We latterly check if it is null in a next line. Let it be this way until Microsoft provide non-nulable guaranties for `Activator` (so until .NET 8, maybe?).

2023-01-24 19:31 UTC, GlebChili commented on gm_dotnet_managed/GmodNET/Lua.cs
> +            if (top is null)
Even if it is not optimized, here is an result with check (https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAWQAUxAKwAeQRjQM5APgYATGABsAlBy499fAGYMx6jYtwMBAVw3a9+7p2qPXDDAAsoEAO5WYfgCiCGAwAA4YfBACYloA3A6OAL6J+qk8xADsappikvGJKdRJQA===) and without (https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAWQAUxAKwAeQRjQM5APgYATGABsAlBy499xAOxrNYyVoDce7gF8aNoA==). Check is just +15 CPU instructions. It is noise.

2023-01-25 03:46 UTC, SupinePandora43 approved these changes
LGTM

2023-01-25 04:37 UTC, merged